### PR TITLE
Refactored and optimised realms

### PR DESCRIPTION
**Pull request by comtihon**
Made some refactoring in big modules, moved tests to tests/eunit, move modules to directories (logically) and split realms to module with gen_server and module with interface for other processes (for better understanging code).
As for optimisation - I made realms ets protected and made reading to in in case of `get_routing` and `get_middleware_list` from calling processes to optimise speed in case of lots of processes.
erwa_realms server only writes to in when adding or removing realm.

### CODE REVIEW

**Comment by comtihon** [comment]
I broke tests with refactoring somehow. Will reopen, when ready.

**Comment by bwegh** [comment]
it is great to have someone else look through the code, thanks for your help!

**Comment by comtihon** [comment]
Fixed all unit tests, ct not working completely, but same in master.
Please see this merge, as realms changes are important.
I'll continue checking project.
It will be very good, if you connect with me via e-mail (my adress is in github profile) as we want to use your project and I have some arch-related questions.

**Comment by bwegh** [comment]
I will have a closer look into all of these changes at the weekend, that is too much for just one evening.
The test are always all passing on travis, so they should stay that way (without just removing all failing ones ;) )

**Comment by bwegh** [comment]
thanks for your help, did some cherry picking on your code :-)

**Pull request closed without merging**
